FROM stefanscherer/golang-windows:1709 AS build

COPY . /code
WORKDIR /code

RUN go build http.go

FROM microsoft/nanoserver:1709

COPY --from=build /code/http.exe /http.exe

EXPOSE 8080

CMD ["\\http.exe"]
