FROM stefanscherer/golang-windows:1.9-insider AS build

COPY . /code
WORKDIR /code

RUN go build http.go

FROM microsoft/nanoserver-insider

COPY --from=build /code/http.exe /http.exe

EXPOSE 8080

CMD ["\\http.exe"]
